apiVersion: platform.stackrox.io/v1
kind: SecurityPolicy
metadata:
  name: "Enforce_Read_Only_Root_Filesystem"
  namespace: rhacs-operator
spec:
  description: "Enforces that the root filesystem of all containers is mounted as read-only (readOnlyRootFilesystem: true)."
  rationale: "Making the root filesystem read-only prevents attackers from writing malicious binaries or modifying critical system files within the container, significantly reducing the attack surface and maintaining container immutability."
  remediation: "Ensure that the security context for all containers in the deployment explicitly sets readOnlyRootFilesystem: true."
  severity: CRITICAL
  categories:
    - "Security Best Practices"
    - "Configuration Management"
  lifecycleStages:
    - "DEPLOY"
  scope:
    - namespace: rhacs-test-policies
  enforcementActions:
    - FAIL_DEPLOYMENT_CREATE_ENFORCEMENT
    - FAIL_DEPLOYMENT_UPDATE_ENFORCEMENT
    - SCALE_TO_ZERO_ENFORCEMENT
    - UNSATISFIABLE_NODE_CONSTRAINT_ENFORCEMENT
  policySections:
    - sectionName: "Container uses read-write root filesystem"
      policyGroups:
        - fieldName: "Read-Only Root Filesystem"
          values:
            - value: "false"