apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-simple-deployment
  namespace: rhacs-test-policies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      containers:
      - name: main-app
        image: quay.io/busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Hello from the emptyDir!" > /my-data/hello.txt
            echo "File written. Now sleeping."
            sleep 3600
            
        volumeMounts:
        - name: cache-volume
          mountPath: /my-data